#Chrono Runner - save file
#Mon Sep 21 13:08:10 GMT+07:00 2026
coins=100
levels.completed=0
levels.unlocked=0,1
shards.0=0
upgrade.DASH=0
upgrade.DOUBLE_JUMP=0
upgrade.REWIND_DURATION=0
upgrade.TIME_ENERGY=0
upgrade.TIME_FREEZE=0
